"""Remove enrollment

Revision ID: 13e47485ce8e
Revises: f3ceb53f61d1
Create Date: 2026-08-15 19:58:46.166139

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '13e47485ce8e'
down_revision: str | Sequence[str] | None = 'f3ceb53f61d1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrollments')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('semester', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('enrollments_subject_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('enrollments_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('enrollments_pkey'))
    )
    # ### end Alembic commands ###
