"""cap_nhat_db

Revision ID: 57c341ccf6d5
Revises: 70155e0eb6af
Create Date: 2026-07-30 22:48:00.552118

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '57c341ccf6d5'
down_revision: str | Sequence[str] | None = '70155e0eb6af'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
