"""rename field in question class

Revision ID: 5d2058c283e0
Revises: c1028338f407
Create Date: 2026-08-11 20:31:07.284975

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5d2058c283e0'
down_revision: str | Sequence[str] | None = 'c1028338f407'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('explanation', sa.String(), nullable=True))
    op.drop_column('questions', 'explaination')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('explaination', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('questions', 'explanation')
    # ### end Alembic commands ###
