"""remove unused models

Revision ID: 62b3770ff744
Revises: 13e47485ce8e
Create Date: 2026-08-26 00:06:22.107699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '62b3770ff744'
down_revision: Union[str, Sequence[str], None] = '13e47485ce8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_citations')
    op.drop_table('notification_read')
    op.drop_table('document_chunks')
    op.drop_table('notifications')
    op.drop_table('quiz_answers')
    op.add_column('chat_messages', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.execute("UPDATE chat_messages SET created_date = NOW() WHERE created_date IS NULL")
    op.alter_column('chat_messages', 'created_date', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'created_date')
    op.create_table('quiz_answers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('quiz_answers_pkey'))
    )
    op.create_table('chat_citations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('similarity_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('document_chunk_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('chat_message_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chat_message_id'], ['chat_messages.id'], name=op.f('chat_citations_chat_message_id_fkey')),
    sa.ForeignKeyConstraint(['document_chunk_id'], ['document_chunks.id'], name=op.f('chat_citations_document_chunk_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_citations_pkey'))
    )
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('notifications_subject_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    op.create_table('document_chunks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('page_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('chunk_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vector_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('document_chunks_document_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('document_chunks_pkey'))
    )
    op.create_table('notification_read',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('read_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('notification_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], name=op.f('notification_read_notification_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notification_read_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('notification_read_pkey'))
    )
    # ### end Alembic commands ###
