"""Add created_by and is_public to Quiz

Revision ID: 68568dfab4a2
Revises: 5d2058c283e0
Create Date: 2026-08-13 20:39:10.951311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68568dfab4a2'
down_revision: Union[str, Sequence[str], None] = '5d2058c283e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('created_by', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('quizzes', sa.Column('is_public', sa.Boolean(), nullable=False, server_default='true'))
    op.create_foreign_key(None, 'quizzes', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.drop_column('quizzes', 'is_public')
    op.drop_column('quizzes', 'created_by')
    # ### end Alembic commands ###
