"""remove quiz_attempt_id from options

Revision ID: 70155e0eb6af
Revises: 1b043119e539
Create Date: 2026-07-28 23:03:25.416189

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '70155e0eb6af'
down_revision: str | Sequence[str] | None = '1b043119e539'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('options_quiz_attempt_id_fkey'), 'options', type_='foreignkey')
    op.drop_column('options', 'quiz_attempt_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('options', sa.Column('quiz_attempt_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('options_quiz_attempt_id_fkey'), 'options', 'quiz_attempts', ['quiz_attempt_id'], ['id'])
    # ### end Alembic commands ###
