"""add fields for chat message and question

Revision ID: c1028338f407
Revises: 57c341ccf6d5
Create Date: 2026-08-10 21:24:44.982055

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c1028338f407'
down_revision: str | Sequence[str] | None = '57c341ccf6d5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('explaination', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'explaination')
    # ### end Alembic commands ###
