"""Sync models

Revision ID: c4c2f13f02a6
Revises: dad3e059c67a
Create Date: 2026-07-27 11:53:01.714454

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'c4c2f13f02a6'
down_revision: str | Sequence[str] | None = 'dad3e059c67a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
