"""Sync models

Revision ID: dad3e059c67a
Revises: 44446afd217b
Create Date: 2026-07-27 11:50:36.720757

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'dad3e059c67a'
down_revision: str | Sequence[str] | None = '44446afd217b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'chat_sessions', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('name', sa.String(), nullable=False))
    gender_enum = sa.Enum('MALE', 'FEMALE', name='gender')
    gender_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('gender', gender_enum, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gender')
    op.drop_column('users', 'name')
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    # ### end Alembic commands ###
