"""make lecturer_id nullable for subjects and documents

Revision ID: e01c44ce3a61
Revises: acd49138d902
Create Date: 2026-09-06 15:33:30.439684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e01c44ce3a61'
down_revision: Union[str, Sequence[str], None] = 'acd49138d902'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'lecturer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('documents_lecturer_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'users', ['lecturer_id'], ['id'], ondelete='SET NULL')
    op.alter_column('subjects', 'lecturer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('subjects_lecturer_id_fkey'), 'subjects', type_='foreignkey')
    op.create_foreign_key(None, 'subjects', 'users', ['lecturer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.create_foreign_key(op.f('subjects_lecturer_id_fkey'), 'subjects', 'users', ['lecturer_id'], ['id'])
    op.alter_column('subjects', 'lecturer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_lecturer_id_fkey'), 'documents', 'users', ['lecturer_id'], ['id'])
    op.alter_column('documents', 'lecturer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
