"""Remove time_limit from quiz

Revision ID: f3ceb53f61d1
Revises: 68568dfab4a2
Create Date: 2026-08-13 21:27:54.087887

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f3ceb53f61d1'
down_revision: str | Sequence[str] | None = '68568dfab4a2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'time_limit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('time_limit', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
